import type { Express } from 'express';
import { accountsRouter } from '../modules/accounts/accounts.routes';
import { notificationsRouter } from '../modules/notifications/notifications.routes';
import { agentRouter } from '../modules/agent/agent.routes';
import { deviceAgentRouter } from '../modules/device-agent/device-agent.routes';
import { provisionRouter } from '../modules/provision/provision.routes';
import { aiRouter } from '../modules/ai/ai.routes';
import { alertsRouter } from '../modules/alerts/alerts.routes';
import { analyticsRouter } from '../modules/analytics/analytics.routes';
import { fleetHealthRouter } from '../modules/fleet-health/fleet-health.routes';
import { apiKeysRouter } from '../modules/apikeys/apikeys.routes';
import { billingRouter } from '../modules/billing/billing.routes';
import { auditRouter } from '../modules/audit/audit.routes';
import { authRouter } from '../modules/auth/auth.routes';
import { bulkRouter } from '../modules/bulk/bulk.routes';
import { calendarRouter } from '../modules/calendar/calendar.routes';
import { catalogRouter } from '../modules/catalog/catalog.routes';
import { apksRouter } from '../modules/apks/apks.routes';
import { hostsRouter } from '../modules/hosts/hosts.routes';
import { emulatorRouter } from '../modules/emulators/emulator.routes';
import { deviceRouter } from '../modules/devices/device.routes';
import { farmRouter } from '../modules/farm/farm.routes';
import { filesRouter } from '../modules/files/files.routes';
import { fingerprintRouter } from '../modules/fingerprint/fingerprint.routes';
import { grantRouter } from '../modules/grants/grant.routes';
import { jobsRouter } from '../modules/jobs/jobs.routes';
import { permissionsRouter } from '../modules/permissions/permissions.routes';
import { pluginsRouter } from '../modules/plugins/plugins.routes';
import { proxyRouter } from '../modules/proxies/proxy.routes';
import { publicRouter } from '../modules/public/public.routes';
import { reportsRouter } from '../modules/reports/reports.routes';
import { rpaRouter } from '../modules/rpa/rpa.routes';
import { schedulerRouter } from '../modules/scheduler/scheduler.routes';
import { snapshotRouter } from '../modules/snapshots/snapshot.routes';
import { socialRouter } from '../modules/social/social.routes';
import { streamRouter } from '../modules/stream/stream.routes';
import { systemRouter } from '../modules/system/system.routes';
import { backupDownloadRouter, backupsRouter } from '../modules/backups/backup.routes';
import { usersRouter } from '../modules/users/users.routes';
import { resourcesRouter } from '../modules/resources/resources.routes';
import { vastRouter } from '../modules/vast/vast.routes';
import { webhooksRouter } from '../modules/webhooks/webhooks.routes';
import { opsRouter } from '../modules/ops/ops.routes';
import { whatsappRouter } from '../modules/whatsapp/whatsapp.routes';
import { workspaceRouter } from '../modules/workspace/workspace.routes';

export function registerRoutes(app: Express): void {
  app.get('/health', (_req, res) => {
    res.json({ ok: true, service: 'vps-emulator-platform' });
  });

  app.use('/auth', authRouter);
  app.use('/devices', deviceRouter);
  app.use('/emulators', emulatorRouter);
  app.use('/jobs', jobsRouter);
  app.use('/plugins', pluginsRouter);
  app.use('/proxies', proxyRouter);
  app.use('/social', socialRouter);
  app.use('/audit', auditRouter);
  app.use('/system', systemRouter);
  app.use('/backups', backupsRouter);
  // Tarayıcı indirmesi: ters vekil bu ön eki API'ye iletir ('/backups/*' panele
  // gider ve orada aynı adlı sayfa olduğu için 404 verirdi).
  app.use('/api-download', backupDownloadRouter);
  app.use('/users', usersRouter);
  app.use('/fingerprints', fingerprintRouter);
  app.use('/schedules', schedulerRouter);
  app.use('/analytics', analyticsRouter);
  app.use('/fleet-health', fleetHealthRouter);
  app.use('/permissions', permissionsRouter);
  app.use('/files', filesRouter);
  app.use('/bulk', bulkRouter);
  app.use('/rpa', rpaRouter);
  app.use('/webhooks', webhooksRouter);
  app.use('/catalog', catalogRouter);
  app.use('/apks', apksRouter);
  app.use('/hosts', hostsRouter);
  app.use('/agent', agentRouter);
  app.use('/provision', provisionRouter);
  app.use('/workspaces', workspaceRouter);
  app.use('/billing', billingRouter);
  app.use('/alerts', alertsRouter);
  app.use('/reports', reportsRouter);
  app.use('/farm', farmRouter);
  app.use('/api-keys', apiKeysRouter);
  app.use('/vast', vastRouter);
  app.use('/stream', streamRouter);
  app.use('/snapshots', snapshotRouter);
  app.use('/grants', grantRouter);
  app.use('/ai', aiRouter);
  app.use('/calendar', calendarRouter);
  app.use('/resources', resourcesRouter);
  app.use('/accounts', accountsRouter);
  app.use('/device-agent', deviceAgentRouter);
  app.use('/notifications', notificationsRouter);
  // WhatsApp conversation layer (chat list, threads, labels) — dashboard-facing.
  app.use('/whatsapp', whatsappRouter);
  app.use('/ops', opsRouter);
  // External/public API (x-api-key only, no JWT) — see modules/public.
  app.use('/public', publicRouter);
}
