import type { Express } from 'express';
import { agentRouter } from '../modules/agent/agent.routes';
import { aiRouter } from '../modules/ai/ai.routes';
import { alertsRouter } from '../modules/alerts/alerts.routes';
import { analyticsRouter } from '../modules/analytics/analytics.routes';
import { apiKeysRouter } from '../modules/apikeys/apikeys.routes';
import { billingRouter } from '../modules/billing/billing.routes';
import { auditRouter } from '../modules/audit/audit.routes';
import { authRouter } from '../modules/auth/auth.routes';
import { bulkRouter } from '../modules/bulk/bulk.routes';
import { calendarRouter } from '../modules/calendar/calendar.routes';
import { catalogRouter } from '../modules/catalog/catalog.routes';
import { hostsRouter } from '../modules/hosts/hosts.routes';
import { emulatorRouter } from '../modules/emulators/emulator.routes';
import { deviceRouter } from '../modules/devices/device.routes';
import { farmRouter } from '../modules/farm/farm.routes';
import { filesRouter } from '../modules/files/files.routes';
import { fingerprintRouter } from '../modules/fingerprint/fingerprint.routes';
import { grantRouter } from '../modules/grants/grant.routes';
import { jobsRouter } from '../modules/jobs/jobs.routes';
import { libraryRouter } from '../modules/library/library.routes';
import { permissionsRouter } from '../modules/permissions/permissions.routes';
import { pluginsRouter } from '../modules/plugins/plugins.routes';
import { proxyRouter } from '../modules/proxies/proxy.routes';
import { referralRouter } from '../modules/referral/referral.routes';
import { reportsRouter } from '../modules/reports/reports.routes';
import { rpaRouter } from '../modules/rpa/rpa.routes';
import { schedulerRouter } from '../modules/scheduler/scheduler.routes';
import { snapshotRouter } from '../modules/snapshots/snapshot.routes';
import { socialRouter } from '../modules/social/social.routes';
import { streamRouter } from '../modules/stream/stream.routes';
import { systemRouter } from '../modules/system/system.routes';
import { usersRouter } from '../modules/users/users.routes';
import { vastRouter } from '../modules/vast/vast.routes';
import { webhooksRouter } from '../modules/webhooks/webhooks.routes';
import { workspaceRouter } from '../modules/workspace/workspace.routes';

export function registerRoutes(app: Express): void {
  app.get('/health', (_req, res) => {
    res.json({ ok: true, service: 'vps-emulator-platform' });
  });

  app.use('/auth', authRouter);
  app.use('/devices', deviceRouter);
  app.use('/emulators', emulatorRouter);
  app.use('/jobs', jobsRouter);
  app.use('/plugins', pluginsRouter);
  app.use('/proxies', proxyRouter);
  app.use('/social', socialRouter);
  app.use('/audit', auditRouter);
  app.use('/system', systemRouter);
  app.use('/users', usersRouter);
  app.use('/library', libraryRouter);
  app.use('/fingerprints', fingerprintRouter);
  app.use('/schedules', schedulerRouter);
  app.use('/analytics', analyticsRouter);
  app.use('/permissions', permissionsRouter);
  app.use('/files', filesRouter);
  app.use('/bulk', bulkRouter);
  app.use('/rpa', rpaRouter);
  app.use('/webhooks', webhooksRouter);
  app.use('/catalog', catalogRouter);
  app.use('/hosts', hostsRouter);
  app.use('/agent', agentRouter);
  app.use('/workspaces', workspaceRouter);
  app.use('/billing', billingRouter);
  app.use('/alerts', alertsRouter);
  app.use('/reports', reportsRouter);
  app.use('/referral', referralRouter);
  app.use('/farm', farmRouter);
  app.use('/api-keys', apiKeysRouter);
  app.use('/vast', vastRouter);
  app.use('/stream', streamRouter);
  app.use('/snapshots', snapshotRouter);
  app.use('/grants', grantRouter);
  app.use('/ai', aiRouter);
  app.use('/calendar', calendarRouter);
}
